"""initial schema

Revision ID: 76a866f90fc7
Revises: 
Create Date: 2026-05-21 16:27:40.388280+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76a866f90fc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_entity_id'), 'event', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_entity_type'), 'event', ['entity_type'], unique=False)
    op.create_index(op.f('ix_event_event_type'), 'event', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_occurred_at'), 'event', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_event_request_id'), 'event', ['request_id'], unique=False)
    op.create_table('idempotency_key',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_idempotency_key_expires_at'), 'idempotency_key', ['expires_at'], unique=False)
    op.create_table('import_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_file_name', sa.String(length=500), nullable=False),
    sa.Column('source_file_hash', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('staged_payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batch_source_file_hash'), 'import_batch', ['source_file_hash'], unique=False)
    op.create_index(op.f('ix_import_batch_status'), 'import_batch', ['status'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_code'), 'project', ['code'], unique=True)
    op.create_table('snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshot_created_at'), 'snapshot', ['created_at'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'site_number', name='uq_site_project_number')
    )
    op.create_index(op.f('ix_site_project_id'), 'site', ['project_id'], unique=False)
    op.create_index(op.f('ix_site_site_number'), 'site', ['site_number'], unique=False)
    op.create_table('site_extended',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('type_history', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_extended_project_id'), 'site_extended', ['project_id'], unique=False)
    op.create_index(op.f('ix_site_extended_site_number'), 'site_extended', ['site_number'], unique=False)
    op.create_index(op.f('ix_site_extended_site_type'), 'site_extended', ['site_type'], unique=False)
    op.create_table('design',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('design_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('vendor_id', sa.Uuid(), nullable=True),
    sa.Column('vendor_status', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status_history', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site_extended.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_assigned_to'), 'design', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_design_design_type'), 'design', ['design_type'], unique=False)
    op.create_index(op.f('ix_design_due_date'), 'design', ['due_date'], unique=False)
    op.create_index(op.f('ix_design_priority'), 'design', ['priority'], unique=False)
    op.create_index(op.f('ix_design_project_id'), 'design', ['project_id'], unique=False)
    op.create_index(op.f('ix_design_site_id'), 'design', ['site_id'], unique=False)
    op.create_index(op.f('ix_design_status'), 'design', ['status'], unique=False)
    op.create_table('floor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floor_site_id'), 'floor', ['site_id'], unique=False)
    op.create_table('sandbox_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('cloned_from', sa.Uuid(), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_name', sa.String(length=200), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site_extended.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_config_expires_at'), 'sandbox_config', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sandbox_config_site_id'), 'sandbox_config', ['site_id'], unique=False)
    op.create_table('map',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('scale', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_floor_id'), 'map', ['floor_id'], unique=False)
    op.create_table('zone',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('floor_id', sa.Uuid(), nullable=False),
    sa.Column('zone_name', sa.String(length=200), nullable=False),
    sa.Column('zone_type', sa.String(length=100), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_floor_id'), 'zone', ['floor_id'], unique=False)
    op.create_index(op.f('ix_zone_project_id'), 'zone', ['project_id'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_number', sa.String(length=50), nullable=False),
    sa.Column('floor_id', sa.Uuid(), nullable=True),
    sa.Column('map_id', sa.Uuid(), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('local_x', sa.Float(), nullable=False),
    sa.Column('local_y', sa.Float(), nullable=False),
    sa.Column('height_ft', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_id'], ['map.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_device_type'), 'device', ['device_type'], unique=False)
    op.create_index(op.f('ix_device_floor_id'), 'device', ['floor_id'], unique=False)
    op.create_index(op.f('ix_device_ip_address'), 'device', ['ip_address'], unique=False)
    op.create_index(op.f('ix_device_map_id'), 'device', ['map_id'], unique=False)
    op.create_index(op.f('ix_device_project_id'), 'device', ['project_id'], unique=False)
    op.create_index(op.f('ix_device_site_number'), 'device', ['site_number'], unique=False)
    op.create_table('cable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_number', sa.String(length=50), nullable=False),
    sa.Column('source_device_id', sa.Uuid(), nullable=False),
    sa.Column('destination_device_id', sa.Uuid(), nullable=False),
    sa.Column('cable_type', sa.String(length=50), nullable=False),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['destination_device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_device_id'], ['device.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cable_destination_device_id'), 'cable', ['destination_device_id'], unique=False)
    op.create_index(op.f('ix_cable_project_id'), 'cable', ['project_id'], unique=False)
    op.create_index(op.f('ix_cable_site_number'), 'cable', ['site_number'], unique=False)
    op.create_index(op.f('ix_cable_source_device_id'), 'cable', ['source_device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cable_source_device_id'), table_name='cable')
    op.drop_index(op.f('ix_cable_site_number'), table_name='cable')
    op.drop_index(op.f('ix_cable_project_id'), table_name='cable')
    op.drop_index(op.f('ix_cable_destination_device_id'), table_name='cable')
    op.drop_table('cable')
    op.drop_index(op.f('ix_device_site_number'), table_name='device')
    op.drop_index(op.f('ix_device_project_id'), table_name='device')
    op.drop_index(op.f('ix_device_map_id'), table_name='device')
    op.drop_index(op.f('ix_device_ip_address'), table_name='device')
    op.drop_index(op.f('ix_device_floor_id'), table_name='device')
    op.drop_index(op.f('ix_device_device_type'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_zone_project_id'), table_name='zone')
    op.drop_index(op.f('ix_zone_floor_id'), table_name='zone')
    op.drop_table('zone')
    op.drop_index(op.f('ix_map_floor_id'), table_name='map')
    op.drop_table('map')
    op.drop_index(op.f('ix_sandbox_config_site_id'), table_name='sandbox_config')
    op.drop_index(op.f('ix_sandbox_config_expires_at'), table_name='sandbox_config')
    op.drop_table('sandbox_config')
    op.drop_index(op.f('ix_floor_site_id'), table_name='floor')
    op.drop_table('floor')
    op.drop_index(op.f('ix_design_status'), table_name='design')
    op.drop_index(op.f('ix_design_site_id'), table_name='design')
    op.drop_index(op.f('ix_design_project_id'), table_name='design')
    op.drop_index(op.f('ix_design_priority'), table_name='design')
    op.drop_index(op.f('ix_design_due_date'), table_name='design')
    op.drop_index(op.f('ix_design_design_type'), table_name='design')
    op.drop_index(op.f('ix_design_assigned_to'), table_name='design')
    op.drop_table('design')
    op.drop_index(op.f('ix_site_extended_site_type'), table_name='site_extended')
    op.drop_index(op.f('ix_site_extended_site_number'), table_name='site_extended')
    op.drop_index(op.f('ix_site_extended_project_id'), table_name='site_extended')
    op.drop_table('site_extended')
    op.drop_index(op.f('ix_site_site_number'), table_name='site')
    op.drop_index(op.f('ix_site_project_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_snapshot_created_at'), table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_index(op.f('ix_project_code'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_import_batch_status'), table_name='import_batch')
    op.drop_index(op.f('ix_import_batch_source_file_hash'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_idempotency_key_expires_at'), table_name='idempotency_key')
    op.drop_table('idempotency_key')
    op.drop_index(op.f('ix_event_request_id'), table_name='event')
    op.drop_index(op.f('ix_event_occurred_at'), table_name='event')
    op.drop_index(op.f('ix_event_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_entity_type'), table_name='event')
    op.drop_index(op.f('ix_event_entity_id'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
